apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-k8-networking
spec:
  title: K8 Networking
  description: An interactive workshop on Kubernetes Networking
  url: https://github.com/samarsinghal/lab-k8-networking
  content:
    image: docker.io/samarsinghal/workshop:latest
    files: github.com/samarsinghal/lab-k8-networking
  vendor: eduk8s.io
  difficulty: intermediate
  duration: 60m
  tags:
  - containers
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: default
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: node-viewer
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
